development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mymystery_development
  pool: 5
  username: root
  password: '123123'
  host: localhost
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mymystery_test
  pool: 5
  username: root
  password: '123123'
  host: localhost
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mymystery_production
  pool: 5
  username: root
  password: '123123'
  host: localhost
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'